name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: Build
        run: |
          cd Reader
          mkdir build
          cd build
          cmake ../ -D CMAKE_BUILD_TYPE=Release
          make
          
      - name: Run tests
        run: |
          cd Reader/bin
          ./test_reader
          
